__app_backup/models/Aplicacion.php
<?php

class Aplicacion extends Eloquent
{

    protected $table = 'aplicaciones';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC');
    }

}

__app_backup/models/Beneficios.php
<?php

class Beneficios extends Eloquent
{

    protected $table = 'beneficios';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/Calidad.php
<?php

class Calidad extends Eloquent
{

    protected $table = 'calidad';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/Contacto.php
<?php

class Contacto extends Eloquent
{

    protected $table = 'contacto';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/ContactoRecebido.php
<?php

class ContactoRecebido extends Eloquent
{

    protected $table = 'contactos_recebidos';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 'true');
    }

}

__app_backup/models/Historia.php
<?php

class Historia extends Eloquent
{

    protected $table = 'historia';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/Homepage.php
<?php

class Homepage extends Eloquent
{

    protected $table = 'homepage';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/Procesos.php
<?php

class Procesos extends Eloquent
{

    protected $table = 'procesos';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/Producto.php
<?php

class Producto extends Eloquent
{

    protected $table = 'productos';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC');
    }

    public function aplicaciones()
    {
        return $this->belongsToMany('Aplicacion', 'producto_aplicacion', 'producto_id', 'aplicacion_id')->orderBy('ordem', 'ASC');
    }

}

__app_backup/models/ProductosEntrada.php
<?php

class ProductosEntrada extends Eloquent
{

    protected $table = 'productos_entrada';

    protected $hidden = [];

    protected $guarded = ['id'];

}

__app_backup/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	protected $table = 'usuarios';

	protected $hidden = array('password', 'remember_token');

	protected $fillable = ['email', 'username', 'password'];

}

__app_backup/controllers/BaseController.php
<?php

class BaseController extends Controller {

	protected $layout = 'frontend.common.template';

	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

    protected function view($path, array $data = [])
    {
        View::share('contacto', Contacto::first());

        $this->layout->content = View::make($path, $data);
    }

}

__app_backup/controllers/BeneficiosController.php
<?php

use \Beneficios, \Aplicacion;

class BeneficiosController extends BaseController {

    public function index()
    {
        $beneficios   = Beneficios::first();
        $aplicaciones = Aplicacion::ordenados()->get();

        return $this->view('frontend.beneficios.index', compact('beneficios', 'aplicaciones'));
    }

    public function show($id)
    {
        $beneficio = Aplicacion::findOrFail($id);

        if (Request::ajax()) {
            return View::make('frontend.beneficios.show', compact('beneficio'));
        } else {
            return Redirect::route('beneficios');
        }
    }

    public function nutricionales()
    {
        if (Request::ajax()) {
            return View::make('frontend.beneficios.nutricionales');
        } else {
            return Redirect::route('beneficios');
        }
    }

}

__app_backup/controllers/CalidadController.php
<?php

use \Calidad;

class CalidadController extends BaseController {

    public function index()
    {
        $calidad = Calidad::first();

        return $this->view('frontend.calidad', compact('calidad'));
    }

}

__app_backup/controllers/HistoriaController.php
<?php

use \Historia;

class HistoriaController extends BaseController {

    public function index()
    {
        $historia = Historia::first();

        return $this->view('frontend.historia', compact('historia'));
    }

}

__app_backup/controllers/HomeController.php
<?php

use \Homepage;

class HomeController extends BaseController {

	public function index()
	{
        $home = Homepage::first();

		return $this->view('frontend.home', compact('home'));
	}

}

__app_backup/controllers/ProcesosController.php
<?php

use \Procesos;

class ProcesosController extends BaseController {

    public function index()
    {
        $procesos = Procesos::first();

        return $this->view('frontend.procesos', compact('procesos'));
    }

}

__app_backup/controllers/ProductosController.php
<?php

use \Producto, \ProductosEntrada;

class ProductosController extends BaseController {

    public function index()
    {
        $productos = Producto::with('aplicaciones')->ordenados()->get();
        $entrada   = ProductosEntrada::first();

        return $this->view('frontend.productos', compact('productos', 'entrada'));
    }

}

__app_backup/views/painel/contactosrecebidos/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <legend>
        <h2>Contatos Recebidos</h2>
    </legend>

    @if(count($contactos_recebidos))
    <table class="table table-striped table-bordered table-hover ">
        <thead>
            <tr>
                <th>Data</th>
                <th>Primer Nombre</th>
                <th>E-mail</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($contactos_recebidos as $contacto)

            <tr class="tr-row @if($contacto->lido != 'true') warning @endif">
                <td>{{ $contacto->created_at }}</td>
                <td>{{ $contacto->primer_nombre }}</td>
                <td>{{ $contacto->email }}</td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.contacto.recebidos.destroy', $contacto->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.contacto.recebidos.show', $contacto->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhum contato recebido.</div>
    @endif

@stop

__app_backup/views/painel/contactosrecebidos/show.blade.php
@section('content')

    <legend>
        <h2>Contato Recebido</h2>
    </legend>

    <div class="form-group">
        <label>Data</label>
        <div class="well">{{ $contacto->created_at }}</div>
    </div>

    <div class="form-group">
        <label>Prefijo</label>
        <div class="well">{{ $contacto->prefijo }}</div>
    </div>

    <div class="form-group">
        <label>Primer Nombre</label>
        <div class="well">{{ $contacto->primer_nombre }}</div>
    </div>

    <div class="form-group">
        <label>Apelido</label>
        <div class="well">{{ $contacto->apelido }}</div>
    </div>

    <div class="form-group">
        <label>Dirección de la calle</label>
        <div class="well">{{ $contacto->direccion1 }}</div>
    </div>

    <div class="form-group">
        <label>Dirección de la calle - Linea 2</label>
        <div class="well">{{ $contacto->direccion2 }}</div>
    </div>

    <div class="form-group">
        <label>Ciudad</label>
        <div class="well">{{ $contacto->ciudad }}</div>
    </div>

    <div class="form-group">
        <label>Estado / Provincia</label>
        <div class="well">{{ $contacto->estado }}</div>
    </div>

    <div class="form-group">
        <label>Código Postal</label>
        <div class="well">{{ $contacto->codigo_postal }}</div>
    </div>

    <div class="form-group">
        <label>País</label>
        <div class="well">{{ $contacto->pais }}</div>
    </div>

    <div class="form-group">
        <label>Empresa</label>
        <div class="well">{{ $contacto->empresa }}</div>
    </div>

    <div class="form-group">
        <label>Número de teléfono</label>
        <div class="well">{{ $contacto->telefono }}</div>
    </div>

    <div class="form-group">
        <label>Correo Electrónico</label>
        <div class="well">{{ $contacto->email }}</div>
    </div>

    <div class="form-group">
        <label>Mensaje</label>
        <div class="well">{{ $contacto->mensaje }}</div>
    </div>

    <a href="{{ route('painel.contacto.recebidos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop